
package ws.hello;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "helloFault", targetNamespace = "http://hello.ws/")
public class HelloFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HelloFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public HelloFault_Exception(String message, HelloFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public HelloFault_Exception(String message, HelloFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ws.hello.HelloFault
     */
    public HelloFault getFaultInfo() {
        return faultInfo;
    }

}
